### ISSUE TITLE
Key of the filenames are garbled

### ISSUE THREAD

**Issue by arun-a-nayagam** [levmel/terraform-multidecoder-yaml_json#13]
Hi @levmel 
Found a strange issue, when using filenames like acp_platinum.yaml and acp_longnam.yaml [note not longname, intentionally misspelt as longnam.yaml]
key for acp_platinum.yaml becomes acp_platinu
key for acp_longnam.yaml becomes acp_alongn

I think it's to do with how the trim function works, I tested it with trimsuffix and that seems to solve the issue.
Perhaps you might want to test and update the code.

Thanks,
Arun

**Comment by arun-a-nayagam** [comment]
Apologies, just after I put the message, I tested trimsuffix with a folder that had just one file called org_test.yaml and that threw an error like this,
```
│ Error: Invalid index
│
│   on ..\modules\orgs\main.tf line 16, in resource "restapi_object" "org":
│   16:     "AccountPlanUuid" : var.acp_uuids["acp_${module.org_yaml.files[each.key].org.account_plan}"],
│     ├────────────────
│     │ each.key is "org_test.yaml"
│     │ module.org_yaml.files is object with 1 attribute "org_test.yaml"
│     │ var.acp_uuids is map of string with 5 elements
│
│ The given key does not identify an element in this collection value
```

**Comment by levmel** [comment]
Hi @arun-a-nayagam,

it's fixed now in v0.2.1. Thank you for the hint!

Best Regards,
Levon

**Comment by arun-a-nayagam** [comment]
Hi @levmel 
data "local_file" "yaml" {
and this
for i, file in data.local_file.yaml_json_standard

doesn't seem to match?

Thanks,
Arun

**Comment by levmel** [comment]
Hi @arun-a-nayagam,

now it should be good in v0.2.1.

Regards,

Levon
