### ISSUE TITLE
Access *.yaml files recursively

### ISSUE THREAD

**Issue by arun-a-nayagam** [levmel/terraform-multidecoder-yaml_json#2]
Hi,

I like this package, but is there a way to support accessing *.yaml files recursively when filepaths is specified like this,
```
filepaths = ["../outer_directory/*.yaml"]
```

And the folder structure could be,
```
outer_directory
     file1.yaml
     file2.yaml
     inner_directory1
           file3.yaml
```

**Comment by levmel** [comment]
Hi Arun,

the ```"*.yaml"``` support is available in the newest module version 0.0.4.

Best Regards,

Levon

**Comment by arun-a-nayagam** [comment]
Hi @levmel,
I tried both `filepaths = ["../outer_directory/*.yaml"]` and `filepaths = ["../outer_directory/**.yaml"]` both didn't select the files recursively, perhaps I am missing something.
Really appreciate your help on this.
Thanks,
Arun

**Comment by levmel** [comment]
Hi @arun-a-nayagam,

the right file path is ["outer_directory/*.yaml"]

You are welcome :)

Kind Regards,
Levon

**Comment by arun-a-nayagam** [comment]
Hi @levmel 
I am totally missing something here,

Here's my actual file directory

![image](https://user-images.githubusercontent.com/25394330/194413754-b6cb2200-fac7-4fd6-9cfe-8d1e920ebe54.png)

And now in modules/account_plans/main.tf, I have this module block,
```
module "acp_yaml" {
  source    = "../read_files"
  filepaths = ["../../layer7_entities/account_plans/*.yaml"]
}
```
So I have to give the prefix ../../ in the filepaths,
When ../../ is prefixed, then it's able to read the yamls (acp_gold.yaml and acp_silver.yaml) not inner_dir/acp_bronze.yaml
If I remove the ../../ prefix, then it's not able to read any of the yamls.

I am using the latest version of your code.

Thanks,
Arun

**Comment by levmel** [comment]
Hi @arun-a-nayagam,

your root main.tf should look like that:

module "yaml_json_decoder" {
  source  = "levmel/yaml_json/multidecoder"
  version = "0.2.1"
  filepaths = ["layer7_entities/account_plans/*.yaml"]
}

module "account_plans" {
   source      = "./modules/account_plans"}
   acp_gold  = module.yaml_json_decoder.files.acp_gold
   acp_silver = module.yaml_json_decoder.files.acp_silver
}

in /modules/account_plans you need to create a variable.tf with this content:

variable "acp_gold" {
   type = any
   description = "Values of acp_gold config."
}

variable "acp_silver" {
   type = any
   description = "Values of acp_silver config."
}

and then you can use those variables in the main.tf of account_plans folder as follows:

var.acp_silver.entry
var.acp_gold.entry

Regards,

Levon

**Comment by arun-a-nayagam** [comment]
Hi @levmel 

I want the list to be dynamic. 
So if someone adds an acp source yaml, then terraform should automatically pick it up.
I have achieved it. Just that the yaml lookup isn't recursive.
So in my case that `inner_dir/acp_bronze.yaml` isn't getting picked up, but the acp_gold.yaml and acp_silver.yaml are getting picked up fine, as they are under `"../../layer7_entities/account_plans"` - the filepath specified.

Thanks,
Arun

**Comment by levmel** [comment]
Hi @arun-a-nayagam,

it shouldn't be recursive, because everyone likes to pick specific config files and not from all branched directories. You can add ```"layer7_entities/account_plans/inner_dir/*.yaml"``` to the filepath attribute of module "yaml_json_decoder" and all the yaml files will be picked from inner_dir all the time.

Regards,
Levon

**Comment by levmel** [comment]
I will close this thread, because it is not an issue. If you have more questions, please open a discussion :)

Thank you,

Levon
